# Generated by Django 4.1.7 on 2023-02-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='نامعلوم', max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(default='نامعلوم', max_length=50, verbose_name='نام خانوادگی')),
                ('admintion_date', models.DateTimeField(max_length=50, verbose_name='تاریخ و ساعت مراجعه')),
                ('age', models.PositiveSmallIntegerField(default='نامعلوم', verbose_name='سن')),
                ('gender', models.CharField(choices=[('1', 'زن'), ('2', 'مرد'), ('3', 'باردار')], max_length=50, verbose_name='جنس')),
                ('transportion', models.CharField(blank=True, choices=[('1', 'آمبولانس خصوصی 115'), ('2', ' آمبولانس خصوصی'), ('3', 'وسیله شخصی'), ('3', 'امداد هوایی')], max_length=50, null=True, verbose_name='نحوه ارجاع')),
                ('other', models.CharField(blank=True, max_length=200, verbose_name='other')),
                ('visit_last24hour', models.BooleanField(verbose_name='مراجعه 24 ساعت قبل')),
                ('pationt_main_complaint', models.CharField(max_length=1000, verbose_name='شکایت اصلی بیمار')),
                ('Alergics', models.CharField(max_length=1000, null=True, verbose_name='سابقه حساسیت دارویی و غذایی')),
                ('level_of_consciousness', models.CharField(choices=[('1', 'A'), ('1', 'V'), ('1', 'P'), ('1', 'U')], max_length=200, verbose_name='level_of_consciousness')),
                ('respiratory_distress', models.BooleanField(verbose_name='دیسترس تنفس')),
                ('airway_risk', models.BooleanField(verbose_name='مخاطره راه هوایی')),
                ('cyanosis', models.BooleanField(verbose_name='سیانوز')),
                ('shock_symptoms', models.BooleanField(verbose_name='علایم شوک')),
                ('Spo2_90', models.BooleanField(verbose_name='Spo2<90')),
                ('Lethargy_and_sleepiness', models.BooleanField(verbose_name='لتارژی و خواب آلودگی')),
                ('Pain_with_severe_distress', models.BooleanField(verbose_name=' درد با دیسترس شدید')),
                ('medical_record', models.CharField(max_length=200, null=True, verbose_name='سابقه پزشکی')),
                ('medication_history', models.CharField(max_length=200, null=True, verbose_name='سابقه دارویی')),
                ('vital_Signs2_BP', models.CharField(max_length=200, verbose_name='vital_Signs2_BP')),
                ('vital_Signs2_RP', models.CharField(max_length=200, verbose_name='vital_Signs2_RP')),
                ('vital_Signs2_RR', models.CharField(max_length=200, verbose_name='vital_Signs2_RR')),
                ('vital_Signs2_T', models.CharField(max_length=200, verbose_name='vital_Signs2_T')),
                ('vital_Signs2_Spo2', models.CharField(max_length=200, verbose_name='vital_Signs2_Spo2')),
                ('Facilities', models.BooleanField(verbose_name='تعداد تسهیلات مورد نظر بیمار اورژانس')),
                ('vital_Signs3_BP', models.CharField(max_length=200, verbose_name='vital_Signs3_BP')),
                ('vital_Signs3_RP', models.CharField(max_length=200, verbose_name='vital_Signs3_RP')),
                ('vital_Signs3_RR', models.CharField(max_length=200, verbose_name='vital_Signs3_RR')),
                ('vital_Signs3_T', models.CharField(max_length=200, verbose_name='vital_Signs3_T')),
                ('vital_Signs3_Spo2', models.CharField(max_length=200, verbose_name='vital_Signs3_Spo2')),
                ('faculties', models.CharField(choices=[('1', 'یک مورد'), ('2', 'هیچ')], max_length=25, verbose_name='تعداد تسهیلات مورد نیاز بیمار در اورژانس')),
                ('level_of_triage', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2, verbose_name='سطح تریاژ بیمار')),
                ('emergency_department', models.CharField(choices=[('1', 'بخش 1'), ('2', 'بخش 4'), ('3', '5 بخش'), ('4', 'بخش 6'), ('5', 'بخش 7'), ('6', 'بخش 8'), ('7', 'CCU'), ('8', 'اتاق عمل'), ('9', 'آنژیوگرافی'), ('10', 'زایمان'), ('11', 'NICU')], max_length=25, verbose_name='ارجاع به کدام قسمت بخش اورژانس')),
                ('triage_nurse_name', models.CharField(max_length=50, null=True, verbose_name='نام و امضای پرستار تریاژ')),
            ],
        ),
    ]
