# Generated by Django 4.1.7 on 2023-02-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localTriage', '0002_alter_triage_vital_signs2_bp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='admintion_date',
            field=models.DateField(max_length=50, verbose_name='تاریخ مراجعه'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='medical_record',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='سابقه پزشکی'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='medication_history',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='سابقه دارویی'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='vital_Signs2_BP',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='vital_Signs2_BP'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='vital_Signs2_RP',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='vital_Signs2_RP'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='vital_Signs2_RR',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='vital_Signs2_RR'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='vital_Signs2_Spo2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='vital_Signs2_Spo2'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='vital_Signs2_T',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='vital_Signs2_T'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='vital_Signs3_BP',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='vital_Signs3_BP'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='vital_Signs3_RP',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='vital_Signs3_RP'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='vital_Signs3_RR',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='vital_Signs3_RR'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='vital_Signs3_Spo2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='vital_Signs3_Spo2'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='vital_Signs3_T',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='vital_Signs3_T'),
        ),
    ]
