# Generated by Django 4.1.7 on 2023-02-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localTriage', '0003_alter_triage_admintion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='admintion_time',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='admintion_date',
            field=models.DateField(null=True),
        ),
    ]
