# Generated by Django 4.1.7 on 2023-02-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localTriage', '0004_triage_admintion_time_alter_triage_admintion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='admintion_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='admintion_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
