# Generated by Django 4.1.7 on 2023-02-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localTriage', '0005_alter_triage_admintion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='admintion_time',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
