# Generated by Django 4.1.7 on 2023-02-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localTriage', '0006_alter_triage_admintion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='admintion_date',
            field=models.DateField(null=True, verbose_name='تاریخ مراجعه'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='admintion_time',
            field=models.DateField(null=True, verbose_name='ساعت مراجعه'),
        ),
    ]
